# Generated by Django 5.2.7 on 2025-11-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="name",
            field=models.CharField(blank=True, default="", max_length=140),
        ),
    ]
