# Generated by Django 5.2.7 on 2025-11-19 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0006_bed"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="beds",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="bed",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bed_list",
                to="rooms.room",
            ),
        ),
    ]
