# Generated by Django 5.2.7 on 2025-11-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="House",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140)),
                ("description", models.TextField()),
                (
                    "price_per_night",
                    models.PositiveIntegerField(
                        help_text="Positive Numbers Only", verbose_name="Price"
                    ),
                ),
                (
                    "pets_allowed",
                    models.BooleanField(
                        default=True,
                        help_text="Does this house allow pets?",
                        verbose_name="Pets Allowed?",
                    ),
                ),
                ("address", models.CharField(max_length=140)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
