# Generated by Django 5.2.7 on 2025-10-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0002_rename_price_house_price_per_night"),
    ]

    operations = [
        migrations.AddField(
            model_name="house",
            name="pet_friendly",
            field=models.BooleanField(default=True),
        ),
    ]
