# Generated by Django 5.2.7 on 2025-11-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0003_house_pet_friendly"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="house",
            name="pet_friendly",
        ),
        migrations.AddField(
            model_name="house",
            name="pets_allowed",
            field=models.BooleanField(
                default=True,
                help_text="Does this house allow pets?",
                verbose_name="Pets allowed?",
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="address",
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name="house",
            name="name",
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name="house",
            name="price_per_night",
            field=models.PositiveIntegerField(
                help_text="Positive numbers only", verbose_name="Price per night"
            ),
        ),
    ]
