# Generated by Django 5.2.7 on 2025-11-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experiences", "0003_alter_experience_host_alter_experience_perks"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="duration",
            field=models.PositiveIntegerField(
                default=60, help_text="Duration in minutes"
            ),
        ),
    ]
