# Generated by Django 5.2.7 on 2025-11-15 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_alter_booking_user"),
        ("rooms", "0006_bed"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="bed",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="rooms.bed",
            ),
        ),
    ]
