# Generated by Django 5.2.7 on 2025-11-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_booking_bed"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="experience_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
