# Generated by Django 5.2.7 on 2025-11-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_booking_experience_end"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="kind",
            field=models.CharField(
                choices=[
                    ("room", "Room"),
                    ("experience", "Experience"),
                    ("bed", "Bed"),
                ],
                max_length=15,
            ),
        ),
    ]
